services:
  - type: web
    name: quizly-ai
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: AUTH_SECRET
        sync: false
      - key: AUTH_TRUST_HOST
        value: "true"
      - key: AUTH_URL
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
